baseURL = "https://wylansford.github.io/"
languageCode = "en-us"
title = "Wyatt Lansford's Blog"
theme = "m10c"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Wyatt Lansford"
  description = "CTO & Co-Founder of Wooz AI | Building the future of AI-driven networking"
  avatar = "/selfie.png"
  favicon = "/favicon.ico"

[[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/wylansford"

[[params.social]]
  icon = "linkedin"
  name = "LinkedIn"
  url = "https://linkedin.com/in/wyattlansford"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[menu.main]]
  identifier = "tech"
  name = "Tech Blog"
  url = "/tech/"

[[menu.main]]
  identifier = "tea"
  name = "Tea Blog"
  url = "/tea/"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1